### ISSUE TITLE
Training actor locally?

### ISSUE THREAD

**Issue by Infinitay** [SwordHolderSH/Mang2Vec#1]
First of all thanks for implementing Mang2Vec. I think your implementation is the only public implementation, so thank you for your work. Secondly, please be patient if I wrongfully make assumptions or mistakes, I'm still new to the field of ML.

I assume `actor.pkl` is the training data the reinforcement? Is it possible to train the model myself with the existing repository of Mang2Vec?

Also, from reading the paper, if we were to train it ourselves, would be have to manually resize the photos to be 128x128 and convert them to grayscale so that they're one channel?

![image](https://user-images.githubusercontent.com/6964154/212474478-af23dab4-f9f1-436e-8952-bfbb5165532a.png)

**Comment by SwordHolderSH** [comment]
Thanks for your attention to our work.

First, "actor. pkl" is the saved weights of the trained actor.

Second, sorry that we have not published the training code yet, since we have not simplified training codes. Besides, I am currently facing doctorate graduation and writing another paper. I will update the code of the training model when I have time.

Third, for the training code, you can refer to the training code at "https://github.com/megvii-research/ICCV2019-LearningToPaint", and then modify some rewards, actor, and drawing modules. Or, when we continue to publish the code.

Forth, our training data is from some mangas we downloaded(e.g., Naruto, Bleach, One piece, dragon ball), and cannot be published due to the copyright of these mangas. These mangas can be found and downloaded easily。

Fifth, we first gray each downloaded manga to 1 channel, and then randomly cut 128 * 128 images in the whole page of a manga. The cutting and graying are very easy to implement, and you can use some python libraries to quickly implement them.
Also, you can set the actor to handel 3 channels, and use the RGB training images.

**Comment by Infinitay** [comment]
Thank you so much for all your insight. I wasn't aware you were the author, thanks for for working on vectorizing with the help of machine learning. I understand you're busy. There's no rush at all. To be honest, I didn't know you were the author so my apologies for that. I wish you the best of luck in your future endeavors, and I believe congratulations are due.

Again, thank you for both your work and the in depth response.

**Comment by ZZZ123ZZ-SOURCE** [comment]
Dear author, it is April 2025, and you still haven't released the training code. Where can we get your training related code?
Finally, thank you for both your work and the in depth response.
